name: Deployment

on: 
  push:
    branches:
      - master
      - continuous-deployment
jobs:
  deployment:
    runs-on: macos-latest
    steps:
      - id: checkout-repo
        name: Read repository
        uses: actions/checkout@v2
      - id: setup-nodejs
        name: Setup NodeJS Environment
        uses: actions/setup-node@v1
      - run: |
          echo $KEYSTORE | base64 -d > ./keystore.jks
          npm install -g turtle-cli
          turtle setup:android
          turtle build:android \
            --keystore-path $(pwd)/keystore.jks \
            --keystore-alias $KEYSTORE_ALIAS
        env:
          KEYSTORE: ${{ secrets.keystore }}
          KEYSTORE_ALIAS: ${{ secrets.keystore_alias }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.keystore_password }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.key_password }}