name: Deployment

on: 
  push:
    branches:
      - master
      - continuous-deployment
jobs:
  deployment:
    runs-on: macos-latest
    steps:
      - id: checkout-repo
        name: Read repository
        uses: actions/checkout@v2
      - id: setup-nodejs
        name: Setup NodeJS Environment
        uses: actions/setup-node@v1
      - run: |
          echo $EXPO_ANDROID_KEYSTORE_BASE64 | base64 -d > ./keystore.jks
          npm install
          npm install -g turtle-cli expo-cli
          npx expo login -u $(EXPO_USERNAME) -p $(EXPO_PASSWORD)
          turtle setup:android
          turtle build:android --keystore-path ./keystore.jks --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS --type app-bundle -o ./artifact.aab
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.KEYSTORE }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
